---
root: true

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: "@babel/eslint-parser"

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

rules:
  no-console: 0
  import/extensions: 0
  import/no-cycle: 0
  no-underscore-dangle: 0
  quotes: 0
  no-param-reassign: 0

settings:
  babel:
    requireConfigFile: false